import type { LightSource } from "./source-definition.js";

export const LIGHT_SOURCE_SET_ID = "abot-light-public-sources";
export const LIGHT_SOURCE_SET_VERSION = 1;

// Explicit origin pages and publisher feeds. This is a bounded source catalog,
// not an Internet index or a promise that every source is currently reachable.
export const DEFAULT_LIGHT_SOURCES: readonly LightSource[] = Object.freeze(
  [
    {
      id: "israel-government",
      title: "Israel Government",
      description:
        "Official Israeli government and Prime Minister's Office publications.",
      keywords: [
        "government",
        "israel",
        "prime minister",
        "ממשלה",
        "ראש ממשלה",
        "ישראל",
      ],
      languages: ["he", "en"],
      entryUrls: [
        "https://www.gov.il/he/departments/prime_ministers_office",
        "https://www.gov.il/en/departments/prime_ministers_office",
      ],
      allowedOrigins: ["https://www.gov.il"],
    },
    {
      id: "uk-government",
      title: "UK Government",
      description:
        "Official UK government leadership and public announcements.",
      keywords: [
        "government",
        "uk",
        "britain",
        "prime minister",
        "politics",
        "ממשלה",
        "בריטניה",
      ],
      languages: ["en"],
      entryUrls: [
        "https://www.gov.uk/government/ministers/prime-minister",
        "https://www.gov.uk/government/organisations/prime-ministers-office-10-downing-street",
      ],
      allowedOrigins: ["https://www.gov.uk"],
    },
    {
      id: "wikipedia-en",
      title: "Wikipedia English",
      description: "General reference articles and current events in English.",
      keywords: [
        "reference",
        "encyclopedia",
        "government",
        "history",
        "science",
        "israel",
        "prime minister",
        "ויקיפדיה",
        "ידע",
      ],
      languages: ["en"],
      entryUrls: [
        "https://en.wikipedia.org/wiki/Portal:Current_events",
        "https://en.wikipedia.org/wiki/Prime_Minister_of_Israel",
      ],
      allowedOrigins: ["https://en.wikipedia.org"],
    },
    {
      id: "wikipedia-he",
      title: "Wikipedia Hebrew",
      description: "General reference articles in Hebrew.",
      keywords: [
        "reference",
        "encyclopedia",
        "israel",
        "ויקיפדיה",
        "ידע",
        "ישראל",
        "ראש ממשלה",
        "היסטוריה",
        "מדע",
      ],
      languages: ["he"],
      entryUrls: [
        "https://he.wikipedia.org/wiki/ראש_ממשלת_ישראל",
        "https://he.wikipedia.org/wiki/ישראל",
      ],
      allowedOrigins: ["https://he.wikipedia.org"],
    },
    {
      id: "openai",
      title: "OpenAI",
      description: "OpenAI product, AI research, and company publications.",
      keywords: [
        "openai",
        "gpt",
        "chatgpt",
        "ai",
        "artificial intelligence",
        "בינה מלאכותית",
        "מודלים",
      ],
      languages: ["en"],
      entryUrls: [
        "https://openai.com/news/rss.xml",
        "https://openai.com/news/",
      ],
      allowedOrigins: ["https://openai.com"],
    },
    {
      id: "nodejs",
      title: "Node.js",
      description:
        "Official Node.js releases, runtime news, and project announcements.",
      keywords: [
        "node",
        "nodejs",
        "node.js",
        "javascript",
        "runtime",
        "release",
        "software",
        "תוכנה",
        "פיתוח",
      ],
      languages: ["en"],
      entryUrls: [
        "https://nodejs.org/en/feed/blog.xml",
        "https://nodejs.org/en/blog",
      ],
      allowedOrigins: ["https://nodejs.org"],
    },
    {
      id: "nasa",
      title: "NASA",
      description: "Space missions, astronomy, and science news from NASA.",
      keywords: [
        "nasa",
        "space",
        "science",
        "astronomy",
        "research",
        "חלל",
        "מדע",
      ],
      languages: ["en"],
      entryUrls: [
        "https://www.nasa.gov/feed/",
        "https://www.nasa.gov/news/all-news/",
      ],
      allowedOrigins: ["https://www.nasa.gov", "https://science.nasa.gov"],
    },
    {
      id: "bbc-world",
      title: "BBC World",
      description: "International news from BBC News.",
      keywords: [
        "world",
        "international",
        "news",
        "politics",
        "government",
        "חדשות",
        "עולם",
        "ממשלה",
      ],
      languages: ["en"],
      entryUrls: ["https://feeds.bbci.co.uk/news/world/rss.xml"],
      allowedOrigins: [
        "https://feeds.bbci.co.uk",
        "https://www.bbc.com",
        "https://www.bbc.co.uk",
        "https://bbc.com",
      ],
    },
    {
      id: "guardian-world",
      title: "The Guardian World",
      description: "International affairs and world news.",
      keywords: ["world", "international", "news", "politics", "חדשות", "עולם"],
      languages: ["en"],
      entryUrls: ["https://www.theguardian.com/world/rss"],
      allowedOrigins: ["https://www.theguardian.com"],
    },
    {
      id: "cbc-world",
      title: "CBC World",
      description: "World news and international reporting.",
      keywords: ["world", "international", "news", "canada", "חדשות", "עולם"],
      languages: ["en"],
      entryUrls: ["https://www.cbc.ca/webfeed/rss/rss-world"],
      allowedOrigins: ["https://www.cbc.ca"],
    },
    {
      id: "geektime",
      title: "Geektime",
      description:
        "Technology, startups, software, and AI reporting in Hebrew.",
      keywords: [
        "technology",
        "ai",
        "gpt",
        "software",
        "startups",
        "טכנולוגיה",
        "בינה מלאכותית",
        "כתבות",
        "תוכנה",
      ],
      languages: ["he"],
      entryUrls: ["https://www.geektime.co.il/feed/"],
      allowedOrigins: ["https://www.geektime.co.il"],
    },
    {
      id: "techcrunch",
      title: "TechCrunch",
      description: "Technology companies, startups, and AI news.",
      keywords: [
        "technology",
        "ai",
        "gpt",
        "software",
        "startups",
        "טכנולוגיה",
        "בינה מלאכותית",
        "כתבות",
      ],
      languages: ["en"],
      entryUrls: ["https://techcrunch.com/feed/"],
      allowedOrigins: ["https://techcrunch.com"],
    },
    {
      id: "ynet",
      title: "Ynet",
      description: "Israeli general news headlines in Hebrew.",
      keywords: [
        "israel",
        "news",
        "politics",
        "ישראל",
        "חדשות",
        "ממשלה",
        "ראש ממשלה",
      ],
      languages: ["he"],
      entryUrls: ["https://www.ynet.co.il/Integration/StoryRss2.xml"],
      allowedOrigins: ["https://www.ynet.co.il"],
    },
    {
      id: "walla",
      title: "Walla News",
      description: "Israeli current affairs and general news in Hebrew.",
      keywords: ["israel", "news", "politics", "ישראל", "חדשות", "ממשלה"],
      languages: ["he"],
      entryUrls: ["https://rss.walla.co.il/feed/1"],
      allowedOrigins: [
        "https://rss.walla.co.il",
        "https://news.walla.co.il",
        "https://www.walla.co.il",
      ],
    },
    {
      id: "times-of-israel",
      title: "The Times of Israel",
      description: "Israeli and regional news in English.",
      keywords: [
        "israel",
        "news",
        "politics",
        "government",
        "prime minister",
        "ישראל",
        "חדשות",
        "ראש ממשלה",
      ],
      languages: ["en"],
      entryUrls: ["https://www.timesofisrael.com/feed/"],
      allowedOrigins: ["https://www.timesofisrael.com"],
    },
    {
      id: "nature",
      title: "Nature",
      description: "Science news and research publications.",
      keywords: [
        "science",
        "research",
        "nature",
        "ai",
        "biology",
        "physics",
        "מדע",
        "מחקר",
      ],
      languages: ["en"],
      entryUrls: ["https://www.nature.com/nature.rss"],
      allowedOrigins: ["https://www.nature.com"],
    },
  ].map((source) =>
    Object.freeze({
      ...source,
      keywords: Object.freeze(source.keywords),
      languages: Object.freeze(source.languages),
      entryUrls: Object.freeze(source.entryUrls),
      allowedOrigins: Object.freeze(source.allowedOrigins),
    }),
  ),
);
