const genericMessage = "ABot Spark could not complete this review. No specific cause is available.";

// Exact content-free codes only. Never turn an arbitrary provider error into UI copy.
const groups = [
  ["macOS Accessibility permission is required. Open Computer access for the exact companion executable to approve. Spark waits up to two minutes for your consent.", ["macos_accessibility_permission_required"]],
  ["macOS Accessibility permission was removed. Re-enable access for the companion in Computer access, then stop and start collection.", ["macos_accessibility_permission_revoked"]],
  ["macOS Accessibility permission was not granted within two minutes. Complete permission setup in Computer access, then stop and start collection to check again.", ["macos_accessibility_permission_timeout"]],
  ["Collection is working through Windows accessibility. Some apps do not expose all visible content; this is a coverage limit, not a connection failure.", ["uia_application_coverage"]],
  ["Collection is working through macOS accessibility. Some apps do not expose all visible content; this is a coverage limit, not a connection failure.", ["ax_application_coverage"]],
  ["Collection is working through Linux accessibility. Some apps do not expose all visible content; this is a coverage limit, not a connection failure.", ["atspi_application_coverage", "wayland_atspi_coverage", "x11_atspi_coverage"]],
  ["The current app is not exposing readable content. Collection can continue when readable content becomes available.", ["accessibility_read_unavailable", "focused_window_unavailable"]],
  ["Rapid screen changes are temporarily muted to avoid collecting repeated activity. Collection resumes after switching windows, editing, or a quiet period.", ["continuous_activity"]],
  ["Collection is paused because this application is excluded in Settings.", ["application_excluded"]],
  ["Collection is paused while the screen is locked or a secure desktop is active.", ["screen_locked_or_secure_desktop", "screen_locked"]],
  ["ABot's own interface is excluded from collection to avoid learning from its own output.", ["runtime_interface_excluded"]],
  ["Collection is outside its configured hours. It resumes during the next collection window.", ["learning_outside_collection_window"]],
  ["Processing is outside its configured hours. Pending activity is kept within its retention limit.", ["learning_outside_processing_window"]],
  ["The computer has no accessible graphical session. Sign in to a desktop session to collect activity.", ["graphical_session_unavailable"]],
  ["The collector cannot verify whether the screen is locked, so collection is paused.", ["session_lock_state_unavailable"]],
  ["Linux accessibility dependencies are missing. Update Computer access setup on this computer.", ["linux_atspi_python_dependencies_missing"]],
  ["Window-change events are unavailable. Collection is using accessibility events with reduced coverage.", ["x11_events_unavailable_atspi_only"]],
  ["The Windows accessibility collector is unavailable. Check Computer access and its permissions.", ["windows_uia_helper_unavailable", "foreground_events_unavailable"]],
  ["The proactive model's explanation was missing or invalid. That attempt did not create a suggestion; collection and learning are separate.", ["proactive_reason_invalid"]],
  ["The proactive model returned an unreadable response. No suggestion was created.", ["proactive_output_invalid_json"]],
  ["The proactive model returned a decision that could not be accepted. No suggestion was created.", ["proactive_decision_invalid", "proactive_none_payload_invalid"]],
  ["The model could not complete a step of the proactive review. No suggestion was created.", ["proactive_staged_output_invalid", "proactive_staged_output_fields_invalid", "proactive_objective_invalid"]],
  ["The proactive suggestion needs a valid title and message before it can be shown.", ["proactive_title_invalid", "proactive_message_invalid"]],
  ["The proactive suggestion referred to missing, changed, or invalid knowledge. It was not delivered.", ["proactive_sources_invalid", "proactive_source_invalid", "proactive_source_stale_or_unknown", "proactive_source_duplicate", "proactive_sources_required"]],
  ["The proactive suggestion had a missing or invalid expiry or review time. It was not delivered.", ["proactive_expiry_required", "proactive_time_invalid", "proactive_time_not_future", "proactive_time_too_distant", "proactive_reference_time_invalid"]],
  ["Choose an available proactive model in Spark Settings before allowing or starting proactive mode.", ["proactive_model_required", "proactive_model_profile_unavailable", "proactive_model_profile_overridden"]],
  ["The proactive review reached its time limit. No suggestion was created.", ["proactive_review_timeout"]],
  ["Proactive mode has reached its daily message limit. It can send suggestions after the daily limit resets.", ["proactive_daily_message_limit_reached"]],
  ["Proactive mode is outside its configured hours. It resumes during the next proactive window.", ["proactive_outside_window"]],
  ["Proactive mode is turned off.", ["proactive_disabled"]],
  ["The proactive review yielded resources to your active conversation.", ["proactive_interactive_preempted"]],
  ["The proactive review was superseded by changed settings or knowledge.", ["proactive_superseded", "proactive_preferences_changed", "proactive_revision_conflict"]],
  ["The proactive review was interrupted. The same knowledge is not retried automatically to avoid repeated model costs.", ["proactive_review_interrupted"]],
  ["The suggestion could not be delivered to a conversation. Check the runtime connection.", ["proactive_session_delivery_unavailable"]],
  ["The proactive activity could not start. Other ABot Spark activities can continue independently.", ["proactive_start_failed"]],
  ["Saved proactive state could not be read safely.", ["proactive_state_invalid", "proactive_state_too_large"]],
  ["The proactive review's context is too large for its allowed limit.", ["proactive_knowledge_context_too_large"]],
  ["Proactive mode could not complete this review. No specific cause is available.", ["proactive_failed"]],
  ["Scheduled knowledge review could not start. Other ABot Spark activities can continue independently.", ["learning_reassessment_start_failed"]],
  ["Scheduled knowledge review is waiting for capacity.", ["learning_reassessment_capacity"]],
  ["Scheduled knowledge review could not finish. Existing knowledge is kept.", ["learning_reassessment_failed"]],
  ["Learning data cleanup could not finish. Check the runtime's storage access.", ["learning_maintenance_failed"]],
  ["No computer is paired for learning. Connect a computer to start collecting.", ["host_not_paired"]],
  ["The paired computer is disconnected. Reconnect it or open computer setup.", ["host_disconnected"]],
  ["The computer connection is unavailable. Connect a computer for learning.", ["host_broker_unavailable"]],
  ["This Host Companion cannot collect learning activity. Install the current companion.", ["host_observations_unsupported"]],
  ["The paired computer did not respond. Check that its companion is running.", ["host_observation_connect_timeout"]],
  ["A Host Companion connection is required to collect computer activity.", ["learning_host_unavailable"]],
  ["The connected computer changed. Connect it again for learning.", ["learning_device_changed"]],
  ["Another runtime is already collecting activity from this computer.", ["host_observations_already_owned"]],
  ["The computer connection request was cancelled.", ["host_observation_cancelled"]],
  ["Allow this activity in Spark Settings before starting it.", ["learning_activity_not_allowed"]],
  ["Choose a learning model in Spark Settings before allowing or starting collection or learning.", ["learning_model_required"]],
  ["The selected learning model is unavailable. Choose another model.", ["learning_model_profile_unavailable"]],
  ["The selected learning model cannot be used for background learning. Choose another model.", ["learning_model_profile_overridden"]],
  ["The learning model could not process activity. Check its configuration in Settings.", ["learning_model_request_failed"]],
  ["The model did not finish its response.", ["output_incomplete"]],
  ["This review reached its time limit before finishing.", ["learning_batch_timeout"]],
  ["Long-term memory or its embedding model is unavailable. Check Memory settings.", ["learning_memory_unavailable"]],
  ["Learning storage is unavailable. Check Memory settings.", ["learning_storage_unavailable"]],
  ["Review progress could not be saved. Processing stopped to avoid repeating completed model work. Earlier saved progress is kept within its retention limit.", ["learning_review_progress_storage_unavailable", "learning_review_progress_capacity"]],
  ["Saved review progress could not be read safely. No changes from this review were applied.", ["learning_review_progress_invalid"]],
  ["Saved review progress reached its retention limit. This review cannot continue from that checkpoint.", ["learning_review_progress_expired"]],
  ["The staged review could not continue safely. No changes from this review were applied.", ["co_worker_review_stage_limit_invalid", "co_worker_review_stage_order_invalid"]],
  ["Collection was turned off.", ["learning_disabled"]],
  ["Processing was paused. Pending activity remains subject to its retention limit.", ["learning_processing_paused"]],
  ["The pending activity was deleted.", ["learning_pending_deleted"]],
  ["Processing stopped before this review finished.", ["learning_stopped"]],
  ["This activity reached its retention limit before the review finished.", ["learning_batch_expired"]],
  ["This review yielded resources to an active conversation.", ["learning_interactive_preempted"]],
  ["This review was superseded by a newer learning state.", ["learning_generation_superseded"]],
  ["One observation is too large for the selected model's context window.", ["learning_observation_exceeds_context"]],
  ["The selected model's context capacity is too small for this review. Choose a model with a larger context window.", [
    "request_context_final_envelope_exceeds_window", "request_context_required_content_exceeds_budget", "learning_review_context_exceeds_budget",
  ]],
  ["Waiting in smaller batches to fit the selected model.", ["learning_batch_partitioned"]],
  ["Waiting because processing is turned off for an application. Pending activity remains subject to expiry and storage limits.", ["learning_application_processing_excluded"]],
  ["This review is waiting for queue space to split safely. Its observations remain pending within the retention limit.", ["learning_partition_capacity"]],
  ["The review referred to activity that could not be verified.", [
    "learning_proposal_source_unknown", "learning_decision_source_unknown", "learning_proposal_device_mismatch", "learning_proposal_source_required",
  ]],
  ["The underlying knowledge changed before this review could be saved.", ["learning_knowledge_conflict"]],
  ["Learning needs its embeddings updated before this review can be saved.", ["learning_embedding_reindex_required"]],
  ["The review tried to change a memory protected by a manual edit.", ["learning_memory_protected"]],
  ["The review could not be saved because its receipt storage limit was reached.", ["learning_receipt_capacity"]],
  ["The proposed memory duplicates an existing item and needs an update instead.", ["learning_duplicate_requires_bound_update"]],
  ["The model returned an invalid request to create a new candidate.", ["learning_create_target_invalid"]],
  ["The model returned a learning decision with missing or unsupported fields. This review was not saved.", ["learning_review_output_contract_invalid"]],
  ["The model returned an unreadable response format.", ["learning_output_invalid_json"]],
  ["The model returned the wrong response structure.", ["learning_output_object_required"]],
  ["The model's response did not include its learning decisions.", ["learning_output_decisions_missing"]],
  ["The model returned its learning decisions in the wrong format.", ["learning_output_decisions_not_array"]],
  ["The model returned more learning decisions than this review allows.", ["learning_output_decision_limit"]],
  ["The model returned a decision that could not be accepted.", [
    "learning_action_invalid", "learning_decision_invalid", "learning_decision_list_invalid",
    "learning_decisions_invalid", "learning_target_invalid", "learning_target_kind_invalid", "learning_review_action_invalid",
    "learning_review_cause_invalid", "learning_reason_invalid", "learning_merge_binding_invalid", "invalid_learning_proposal",
  ]],
  ["The review referred to an item that could not be found.", ["learning_decision_target_unknown", "learning_merge_source_unknown"]],
  ["The review requested more than one change to the same item.", ["learning_decision_target_repeated"]],
  ["The model returned an invalid candidate score.", ["learning_score_invalid", "learning_certainty_invalid"]],
  ["The model returned a reinforcement decision that could not be accepted.", ["learning_reinforcement_invalid"]],
  ["The proposed content is not valid for a memory.", ["learning_content_invalid"]],
  ["The proposed content exceeds the memory size limit.", ["learning_content_exceeds_limit"]],
  ["The proposed memory was blocked because it may contain sensitive information.", ["learning_content_sensitive"]],
  ["The candidate could not be saved because its identity conflicts with an existing item.", ["learning_candidate_identity_conflict", "learning_candidate_identity_duplicate"]],
  ["The candidate expired before this review could update it.", ["learning_candidate_expired"]],
  ["Some saved learning data could not be read safely.", [
    "learning_candidate_certainty_corrupt", "learning_candidate_embedding_missing", "learning_candidate_score_corrupt",
    "learning_candidate_vector_binding_corrupt", "learning_candidate_vector_corrupt", "learning_candidates_corrupt",
    "learning_maturation_store_corrupt", "learning_receipts_corrupt", "invalid_learning_state",
  ]],
  ["The learning policy contains an invalid setting.", ["learning_maturation_policy_invalid"]],
  ["The model returned an invalid future review time.", ["learning_reconsideration_invalid", "learning_reconsideration_not_future"]],
  ["The review requested a change that is not allowed without new supporting activity.", ["learning_review_cannot_raise_score", "learning_review_cannot_reinforce"]],
  ["The scheduled review included activity it was not allowed to use.", ["learning_review_observations_unexpected"]],
  ["This item is not due for another review yet.", ["learning_review_target_not_due"]],
  ["The embedding configuration changed during this review.", ["long_term_memory_embedding_binding_changed"]],
  ["The embedding request contained no usable text.", ["long_term_memory_embedding_input_empty"]],
  ["The embedding provider returned data that could not be used.", ["long_term_memory_embedding_response_invalid", "long_term_memory_embedding_vector_count_invalid"]],
  ["The collected batch could not be read safely.", ["invalid_learning_batch", "invalid_learning_batch_expiry"]],
  ["The daily model-call limit was reached. Eligible work can continue after it resets.", ["co_worker_model_daily_budget_exhausted"]],
  ["The daily embedding-call limit was reached. Eligible work can continue after it resets.", ["co_worker_embedding_daily_budget_exhausted"]],
  ["The daily embedding-text limit was reached. Eligible work can continue after it resets.", ["co_worker_embedding_character_budget_exhausted"]],
  ["The available model capacity is busy. This review must wait.", ["co_worker_resources_busy"]],
  ["Computer activity collection is not supported on this platform.", ["platform_unsupported"]],
  ["Computer activity collection needs a dependency that is unavailable.", ["macos_swift_tools_unavailable", "collector_dependency_unavailable"]],
  ["The computer activity collector could not start.", ["collector_start_failed"]],
  ["The computer activity collector returned data that could not be accepted.", ["collector_output_limit", "collector_protocol_invalid"]],
  [genericMessage, ["learning_failed"]],
];
const messages = Object.freeze(Object.fromEntries(groups.flatMap(([message, codes]) => codes.map(code => [code, message]))));

export function learningFailureCopy(reason) {
  if (typeof reason === "string" && Object.hasOwn(messages, reason)) return { message: messages[reason], code: reason };
  return { message: genericMessage, code: null };
}
