export function findAppDom(documentRoot = document) {
  return {
    app: documentRoot.getElementById("app"),
    homeWorkspaceButton: documentRoot.getElementById("homeWorkspaceButton"),
    homeWorkspacePanel: documentRoot.getElementById("homeWorkspacePanel"),
    homeDashboardRoot: documentRoot.getElementById("homeDashboardRoot"),
    chatWorkspaceButton: documentRoot.getElementById("chatWorkspaceButton"),
    schedulesWorkspaceButton: documentRoot.getElementById(
      "schedulesWorkspaceButton",
    ),
    schedulesWorkspacePanel: documentRoot.getElementById(
      "schedulesWorkspacePanel",
    ),
    closeSchedulesWorkspaceButton: documentRoot.getElementById(
      "closeSchedulesWorkspaceButton",
    ),
    schedulesRoot: documentRoot.getElementById("schedulesRoot"),
    configWorkspaceButton: documentRoot.getElementById("configWorkspaceButton"),
    chatPanel: documentRoot.querySelector(".chat-panel"),
    sessionsPanel: documentRoot.querySelector(".sessions-panel"),
    configWorkspacePanel: documentRoot.getElementById("configWorkspacePanel"),
    closeConfigWorkspaceButton: documentRoot.getElementById(
      "closeConfigWorkspaceButton",
    ),
    connectionLabel: documentRoot.getElementById("connectionLabel"),
    environmentSelect: documentRoot.getElementById("environmentSelect"),
    agentPickerButton: documentRoot.getElementById("agentPickerButton"),
    agentPickerMenu: documentRoot.getElementById("agentPickerMenu"),
    newSessionButton: documentRoot.getElementById("newSessionButton"),
    refreshSessionsButton: documentRoot.getElementById("refreshSessionsButton"),
    closeSessionsButton: documentRoot.getElementById("closeSessionsButton"),
    sessionsToggleButton: documentRoot.getElementById("sessionsToggleButton"),
    sessionSearchInput: documentRoot.getElementById("sessionSearchInput"),
    sessionsCount: documentRoot.getElementById("sessionsCount"),
    sessionsList: documentRoot.getElementById("sessionsList"),
    sessionTitle: documentRoot.getElementById("sessionTitle"),
    agentModeButton: documentRoot.getElementById("agentModeButton"),
    agentModeMenu: documentRoot.getElementById("agentModeMenu"),
    permissionModeButton: documentRoot.getElementById("permissionModeButton"),
    permissionModeMenu: documentRoot.getElementById("permissionModeMenu"),
    modelSelect: documentRoot.getElementById("modelSelect"),
    modelSelectButton: documentRoot.getElementById("modelSelectButton"),
    modelSelectValue: documentRoot.getElementById("modelSelectValue"),
    modelSelectMenu: documentRoot.getElementById("modelSelectMenu"),
    messagesList: documentRoot.getElementById("messagesList"),
    runtimeSetupGuide: documentRoot.getElementById("runtimeSetupGuide"),
    messageStatusRegion: documentRoot.getElementById("messageStatusRegion"),
    jumpToLatestButton: documentRoot.getElementById("jumpToLatestButton"),
    composerForm: documentRoot.getElementById("composerForm"),
    attachmentButton: documentRoot.getElementById("attachmentButton"),
    attachmentInput: documentRoot.getElementById("attachmentInput"),
    attachmentPreview: documentRoot.getElementById("attachmentPreview"),
    composerInput: documentRoot.getElementById("composerInput"),
    composerContextWindow: documentRoot.getElementById("composerContextWindow"),
    composerPlan: documentRoot.getElementById("composerPlan"),
    composerSubmitControl: documentRoot.getElementById("composerSubmitControl"),
    sendButton: documentRoot.getElementById("sendButton"),
    sendButtonLabel: documentRoot.getElementById("sendButtonLabel"),
    sendNextMenuButton: documentRoot.getElementById("sendNextMenuButton"),
    sendNextMenu: documentRoot.getElementById("sendNextMenu"),
    sendNextButton: documentRoot.getElementById("sendNextButton"),
    refreshRuntimeButton: documentRoot.getElementById("refreshRuntimeButton"),
    runtimeStatus: documentRoot.getElementById("runtimeStatus"),
    refreshLogsButton: documentRoot.getElementById("refreshLogsButton"),
    runtimeLogs: documentRoot.getElementById("runtimeLogs"),
    refreshHealthButton: documentRoot.getElementById("refreshHealthButton"),
    healthStatus: documentRoot.getElementById("healthStatus"),
    refreshConfigButton: documentRoot.getElementById("refreshConfigButton"),
    configStatus: documentRoot.getElementById("configStatus"),
    configDashboard: documentRoot.getElementById("configDashboard"),
    panelBackdrop: documentRoot.getElementById("panelBackdrop"),
    toastRegion: documentRoot.getElementById("toastRegion"),
    operationsTabButtons: [
      ...documentRoot.querySelectorAll(".operations-tab-button"),
    ],
    operationsTabPages: [
      ...documentRoot.querySelectorAll(".operations-tab-page"),
    ],
  };
}
