export function createAppState() {
  return {
    config: null,
    connected: false,
    sessions: [],
    pinnedSessionIds: [],
    sessionModes: {},
    sessionModels: {},
    lastModelByEnvironment: {},
    agentMode: "reasoning",
    supportedAgentModes: ["fast", "reasoning", "deep", "auto"],
    agentModeMenuOpen: false,
    permissionModeMenuOpen: false,
    agentPickerOpen: false,
    busySessionIds: new Set(),
    messages: [],
    events: [],
    taskProgressByRequest: new Map(),
    contextWindowByRequest: new Map(),
    submittedToolApprovalIds: new Set(),
    requestMessages: new Map(),
    currentSessionId: "",
    activeRequestId: "",
    sessionViewVersion: 0,
    lastSeqByRequest: new Map(),
    modelProfiles: [],
    defaultModelProfileId: "",
    runtimeAvailability: { status: "loading" },
    pendingAttachments: [],
    pendingAttachmentUploadCounts: new Map(),
    composerAttachmentGeneration: 0,
    composerSending: false,
    composerQueueDrainingScopes: new Set(),
    composerQueueRecoveredReleaseTokens: new Set(),
    activeComposerQueueRecovery: null,
    sessionQuery: "",
  };
}
