import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

import { format } from "prettier";

const sourcePath = join(
  process.cwd(),
  "src",
  "shared",
  "model-step-registry-data.json",
);
const outputPath = join(
  process.cwd(),
  "src",
  "shared",
  "model-step-registry.generated.ts",
);

const source = JSON.parse(await readFile(sourcePath, "utf-8")) as unknown;
const steps = requireRegistrySteps(source);
const generated = await format(
  [
    "// Generated by scripts/write-model-step-registry.ts.",
    "// Edit model-step-registry-data.json, then regenerate this file.",
    'import type { RegisteredModelInvocationStepDefinition } from "./model-step-registry.types.js";',
    "",
    "export const GENERATED_MODEL_INVOCATION_STEP_REGISTRY =",
    `${JSON.stringify(steps, null, 2)} as const satisfies Readonly<`,
    "  Record<string, RegisteredModelInvocationStepDefinition>",
    ">;",
    "",
  ].join("\n"),
  { parser: "typescript" },
);

if (process.argv.includes("--check")) {
  const current = await readFile(outputPath, "utf-8").catch(() => "");
  if (current !== generated) {
    throw new Error(
      "Generated model-step registry is stale. Run npm run generate:model-step-registry.",
    );
  }
  console.log("generated model-step registry is current");
} else {
  await writeFile(outputPath, generated, "utf-8");
  console.log(`wrote ${outputPath}`);
}

function requireRegistrySteps(
  value: unknown,
): Readonly<Record<string, unknown>> {
  if (!isRecord(value) || !isRecord(value.steps)) {
    throw new Error(
      "model-step-registry-data.json must contain a steps object",
    );
  }
  return value.steps;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
