import { PUBLIC_HTTP_LIMITS } from "../../../src/shared/public-http/limits.js";

export const WEB_LIMITS = Object.freeze({
  ...PUBLIC_HTTP_LIMITS,
  queryMaxChars: 400,
  queryMaxWords: 50,
  searchQueries: 5,
  searchResultsPerQuery: 5,
  searchQueryConcurrency: 3,
  searchSourceFetches: 6,
  searchSourceConcurrency: 3,
  targetReadableSources: 3,
  fetchUrls: 3,
  fetchConcurrency: 3,
  outputChars: 16_000,
  pageOutputChars: 12_000,
  sourceOutputChars: 3_000,
  searchTotalTimeoutMs: 30_000,
  outputBytes: 48 * 1024,
  upstreamUrlChars: 4_096,
  searchResultUrlChars: 1_024,
  upstreamTitleChars: 180,
  upstreamSnippetChars: 800,
  retryAttempts: 2,
  retryBaseMs: 750,
} as const);
